server:
  ssl:
    enabled: true
    key-store: classpath:cert.p12
    key-store-password: 123
    key-store-type: pkcs12
  #    key-alias: springboot
  #    key-password:
  port: 8443

spring:
  application:
    name: SimpleSpringBootCacheDemoApplication
  output:
    ansi:
      enabled: ALWAYS

# Spring Doc support
springdoc:
  packagesToScan: com.techienotes.controller

logging:
  level:
    org:
      springframework:
        web: INFO